modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/unilock/YepTwo/issues"
license = "MIT"

[[mixins]]
config="yeptwo.mixins.json"

[[mixins]]
config="yeptwo-neoforge.mixins.json"

[[mods]]
modId = "yeptwo"
version = "${version}"
displayName = "Yep"
authors = "unilock"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.yeptwo]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yeptwo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
